### ISSUE TITLE
Testing in development with letter_opener?

### ISSUE THREAD

**Issue by mmahalwy** [eddiezane/sendgrid-actionmailer#100]
Is it possible? :)

**Comment by tyrauber** [comment]
You can use either letter_opener or sendgrid-actionmailer by configuring action_mailer in your environment configuration, but you can't use both at the same time, as both are action_mailer delivery_methods and you can only use one delivery_method per environment (as far as I know).

**Comment by mmahalwy** [comment]
@tyrauber makes sense. what would you suggest as the best way to test in development?

**Comment by tyrauber** [comment]
hi @mmahalwy, it really depends on your implementation and what you are trying to test.  If you aren't using Sendgrid Templates and using ActionMailer templates, I'd just use letter opener in development:
```
      config.action_mailer.delivery_method = :letter_opener
      config.action_mailer.perform_deliveries = true
```
If you are using templates, then you'd need to use the sendgrid-actionmailer delivery_method in development as well in order to "preview" the emails. But you need to be really careful because your dev environment is now sending emails out int o the real world. If you are using the gem in a development environment and sending real emails, I'd suggest using a ActiveMailer intercepter to limit distribution to only specific email addresses.
