### ISSUE TITLE
Does not load when Rails inflection has been set for 'SendGrid'

### ISSUE THREAD

**Issue by boardfish** [eddiezane/sendgrid-actionmailer#89]
Setting an inflection for `SendGrid` means we can make an exception to Rails' filenaming schemes. We can name models `SendGrid...` and not have to name files `send_grid_....`. However, it's introduced an issue here relating to `sendgrid-actionmailer`. The gem registers an ingress using the module name `ActionMailbox::Ingresses::Sendgrid`, but the previous acronym definition means the lookup expects `SendGrid`.

`config/initializers/inflections.rb`:

```ruby
# frozen_string_literal: true

ActiveSupport::Inflector.inflections(:en) do |inflect|
  ...
  inflect.acronym 'SendGrid'
end
```

When running in production, where I use `sendgrid-actionmailer`:

```
/app/vendor/bundle/ruby/2.7.0/gems/actionmailbox-6.0.3.2/app/controllers/action_mailbox/ingresses/sendgrid/inbound_emails_controller.rb:47:in `<module:ActionMailbox>': uninitialized constant ActionMailbox::Ingresses::Sendgrid (NameError)
Did you mean?  ActionMailbox::Ingresses::SendGrid
SendGrid
```

There are a couple of questions I have as I write this:

- Is this issue better suited to [rails/rails](https://github.com/rails/rails)? Potentially, it might concern the inflector more than the gem, but I'm not sure.
- Is there anything that can be done to prevent or fix this from within the gem, temporarily or otherwise?

**Comment by tyrauber** [comment]
@boardfish, Yeah, I think this is a naming convention, Rails / ActiveSupport::Inflector issue, not a gem specific issue.  

This gem is a pretty basis library implementation. It contains a  Railtie initializer to add_delivery_method to ActionMailer::Base, and a module class containing the new delivery_method.   Further, the class definition [SendGrid](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/lib/sendgrid_actionmailer.rb#L11) isn't even defined in this gem but in the `sendgrid-ruby` gem, which this gem uses to interface with the SendGrid API.

Easiest fix is use a different naming convention. Otherwise, post to stackoverflow in regards to using ActiveSupport::Inflector with a class conflict.  Hope that helps.

**Comment by boardfish** [comment]
Thanks for the quick response. I figured I might need to take that route. I'll look into it and comment findings here for the benefit of anyone else who deals with something similar.

**Comment by boardfish** [comment]
Made a StackOverflow post [here](https://stackoverflow.com/questions/63602277/using-activesupportinflector-with-a-class-conflict).

**Comment by boardfish** [comment]
Mirroring the solution I found:

Defining inflections on `ActiveSupport::Inflections` affects how they're loaded globally. Thanks to the [Rails docs](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#customizing-inflections), I figured out that you can override inflections on Rails' loader. I ended up needing to add the following to an initializer (`.rb` file under `config/initializers`):

```
# frozen_string_literal: true

Rails.autoloaders.each do |autoloader|
  autoloader.inflector.inflect(
    'sendgrid' => 'Sendgrid'
  )
end
```

This restores the default as far as the loader is aware.
