### ISSUE TITLE
How do I enable sandbox mode in environment file?

### ISSUE THREAD

**Issue by lremes** [eddiezane/sendgrid-actionmailer#91]
We want to use SendGrid sandbox mode to test our email sending.
However, I'm unable to get it work. I've tried the code below, but the email is still sent:
```
config.action_mailer.delivery_method = :sendgrid_actionmailer
config.action_mailer.sendgrid_actionmailer_settings = {
	api_key: Rails.application.credentials.dig(:sendgrid, :rest_api_key),
	raise_delivery_errors: true,
	mail_settings: {
		sandbox_mode: {
			enable: true
		}
	}
}
```

What am I doing wrong?

**Comment by tyrauber** [comment]
@lremes, That is completely sane expected behavior.  Unfortunately, master doesn't work like that.  mail_settings, such as sandbox can only be applied on individual mail instances and not globally through the sendgrid_actionmailer_settings configuration. Which is dumb. 

Check it out the branch `feature/global_mail_settings`.  I made some minor changes to enable that functionality.  Confirm it works as expected, and I'll merge and cut a new build.  `gem 'sendgrid-actionmailer', github: eddiezane/sendgrid-actionmailer', branch: 'feature/global_mail_settings'`

Thanks for the suggestion.

**Comment by gogiel** [comment]
I'm not the author of the original issue but I can confirm that the fix works as expected :+1:
