### ISSUE TITLE
Feature request: Make it possible to config request timeout

### ISSUE THREAD

**Issue by hoangtuanictvn** [eddiezane/sendgrid-actionmailer#97]
Hello, I'm using your sendgrid-actionmailer gem now. And I make this request to hope that you can add the feature to pass the http_options like timeout from config of actionmailer to sendgrid-ruby to set the timeout for sendgrid API request as below.

```
config.action_mailer.sendgrid_actionmailer_settings = {
  api_options: {
    http_options: {
      open_timeout: x,
      write_timeout: x
      ...
    }
  }
  ...
}
```

I had read some issues of the sendgrid/ruby-http-client gem. In sendgrid/ruby-http-client#20 PR, http_options were added, so I hope it is possible to config in your gem.

**Comment by tyrauber** [comment]
Hello @hoangtuanictvn, sendgrid-actionmailer doesn't use sendgrid/ruby-http-client directly, but by way of sendgrid/sendgrid-ruby.  As far as I can tell, [sendgrid-ruby doesn't implement the http_options](https://github.com/sendgrid/sendgrid-ruby/blob/443ac7d034390792730130f1510491ff806f875f/lib/sendgrid/base_interface.rb#L34) provided by  [sendgrid/ruby-http-client#20](https://github.com/sendgrid/ruby-http-client/pull/20). For sendgrid-actionmailer to be able to implement this feature, sendgrid-ruby would need to utilize these options and expose them through it's configuration options, so that sendgrid-actionmailer could pass the options to ruby-http-client through sendgrid-ruby.

**Comment by hoangtuanictvn** [comment]
@tyrauber 
Sorry for my mistake.
And thank you to figure out to me its problem. I had been opened an issue at there sendgrid/sendgrid-ruby/issues/449. I hope that it can be added as soon as possible. Could I notice to you again when the problem of that issue was solved?
